# -*- coding: utf-8 -*-
"""all_checks.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14ToDkViE-e6tMYj86HDbGcpAVAwz5Z1Q
"""

def test():
  Return 345

def main():
  pass

print(test())
main()

